/*
 * GPIO.c
 *
 *  Created on: Mar 14, 2023
 *      Author: Wels
 */
#include "GPIO.h"

void GPIO_LEDS_Init(void)
{
	// LED 1 -> PB0
	// CLOCK ENABLE
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	// SALIDA
	GPIOB->MODER |= GPIO_MODER_MODE0_0;
	// PUSH PULL
	GPIOB->OTYPER &= ~(GPIO_OTYPER_OT0);
	// LOW SPEED
	GPIOB->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR0);
	// NO PULL UP NO PULL DOWN
	GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPD0);

	// LED 2 -> PB7
	// SALIDA
	GPIOB->MODER |= GPIO_MODER_MODE7_0;
	// PUSH PULL
	GPIOB->OTYPER &= ~(GPIO_OTYPER_OT7);
	// LOW SPEED
	GPIOB->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR7);
	// NO PULL UP NO PULL DOWN
	GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPD7);

	// PD7
	// CLOCK ENABLE
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
	// SALIDA
	GPIOD->MODER |= GPIO_MODER_MODE7_0;
	// PUSH PULL
	GPIOD->OTYPER &= ~(GPIO_OTYPER_OT7);
	// LOW SPEED
	GPIOD->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR7);
	// NO PULL UP NO PULL DOWN
	GPIOD->PUPDR &= ~(GPIO_PUPDR_PUPD7);
}

void GPIO_LED1_Toggle(void)
{
	GPIOB->ODR ^= GPIO_ODR_OD0;// XOR
}

void GPIO_LED1_Write(Gpio_State state)
{
	if(state == HIGH)
	{
		GPIOB->ODR |= GPIO_ODR_OD0;
	}
	else
	{
		GPIOB->ODR &= ~GPIO_ODR_OD0;
	}
}

void GPIO_BOT_Init(void)
{
	//PC13
	// CLOCK ENABLE
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	// ENTRADA
	GPIOC->MODER &= ~(GPIO_MODER_MODE13);
	// PUSH PULL
	GPIOC->OTYPER &= ~(GPIO_OTYPER_OT13);
	// LOW SPEED
	GPIOC->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR13);
	// NO PULL UP NO PULL DOWN
	GPIOC->PUPDR &= ~(GPIO_PUPDR_PUPD13);
}

Gpio_State GPIO_BOT_Read(void)
{
	if(GPIOC->IDR & GPIO_IDR_ID13)
	{
		return HIGH;
	}
	else
	{
		return LOW;
	}
}

// PD7
void GPIO_PD7_Toggle(void)
{
	GPIOD->ODR ^= GPIO_ODR_OD7;// XOR
}
