
#include "RCC.h"

void SystemClock(void)
{
	// AND -> 1 AND 0 = 0
	RCC->PLLCFGR &= ~(RCC_PLLCFGR_PLLM | RCC_PLLCFGR_PLLN | RCC_PLLCFGR_PLLP);
	RCC->PLLCFGR |= PLL_N<<6 | PLL_M<<0 | PLL_P<<16;

	//HSE ON
	RCC->CR |= RCC_CR_HSEON;
	while((RCC->CR &RCC_CR_HSERDY) == 0);

	// PLL ON
	RCC->PLLCFGR |= RCC_PLLCFGR_PLLSRC;
	RCC->CR |= RCC_CR_PLLON;
	while((RCC->CR &RCC_CR_PLLRDY) == 0);

	// FLASH
	FLASH->ACR &= ~(FLASH_ACR_LATENCY);
	FLASH->ACR |= FLASH_ACR_LATENCY_5WS;
	FLASH->ACR |= FLASH_ACR_PRFTEN;

	// SW -> PLL
	RCC->CFGR &= ~(RCC_CFGR_SW);
	RCC->CFGR |= (RCC_CFGR_SW_PLL);
	while((RCC->CFGR & RCC_CFGR_SWS_PLL) == 0);

	// AHB
	RCC->CFGR &= ~(RCC_CFGR_HPRE);

	// APB1
	RCC->CFGR &= ~(RCC_CFGR_PPRE1);
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV4;

	// APB2
	RCC->CFGR &= ~(RCC_CFGR_PPRE2);
	RCC->CFGR |= RCC_CFGR_PPRE2_DIV2;
}
